print("Welcome to the Band Name Generator.")
City_Name = input("What's name of the city you grew up in?\n")
Pet_Name = input("What's the name of a pet?\n")
Band_Name = (City_Name + " " + Pet_Name)
print("Your Band Name is : \n" + Band_Name)
